services:
  camunda:
    image: camunda/camunda-bpm-platform:run-7.23.0
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://postgres:5432/postgres?ApplicationName=Camunda
      DB_USERNAME: camunda
      DB_PASSWORD: camunda
    command: ["./camunda.sh", "--rest", "--webapps"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/camunda/app/welcome/default/#!/login"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./../../etc/bpmns:/camunda/configuration/resources

  camundamcp:
    build:
      context: ../
      dockerfile: src/CamundaMcp/Dockerfile
    depends_on:
      - camunda
    environment:
      CAMUNDA_URL: http://camunda:8080
    ports:
      - "5000:5000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
    ports:
      - "5432:5432"
